
services:

  dawnbot:

    build: .               
    container_name: dawnbot
    working_dir: /bot
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    env_file:
      - .env
