version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: dawnbot_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"

  dawnbot:
    build: .
    container_name: dawnbot
    working_dir: /bot
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - API_BASE_URL=http://host.docker.internal:3000
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
